version: '3.3'

volumes:
  pg_data:
  media_volume:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: anquientas/foodgram_backend
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static_volume:/app/backend_static
      - media_volume:/app/media
  frontend:
    image: anquientas/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: anquientas/foodgram_gateway
    env_file: ../.env
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - media_volume:/usr/share/nginx/html/media
      - static_volume:/usr/share/nginx/html/backend_static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
