# Generated by Django 3.2.16 on 2024-03-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240329_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'default_related_name': 'ingredients_recipes', 'verbose_name': 'Продукты рецепта', 'verbose_name_plural': 'Продукты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('author',), 'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
    ]
