# Generated by Django 3.2.16 on 2024-04-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240401_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите меру (единицу измерения)', max_length=200, verbose_name='Мера'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите уникальный слаг', max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
