# Generated by Django 3.2.16 on 2024-03-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('id',), 'verbose_name': 'Мои подписки', 'verbose_name_plural': 'Мои подписки'},
        ),
    ]
